---
apiVersion: v1
kind: Service
metadata:
  name: nperf
  labels:
    app: nperf
spec:
  publishNotReadyAddresses: true
  clusterIP: None
  ports:
    - port: 9999
      name: http1
    - port: 10000
      name: http2
  selector:
    app: nperf
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nperf
  labels:
    app: nperf
spec:
  serviceName: nperf
  podManagementPolicy: Parallel
  replicas: 6
  selector:
    matchLabels:
      app: nperf
  template:
    metadata:
      name: nperf
      labels:
        app: nperf
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - nperf
              topologyKey: "kubernetes.io/hostname"
      containers:
        - name: nperf
          image: "quay.io/minio/nperf"
          imagePullPolicy: Always
          args:
            - nperf-0.nperf.${NAMESPACE}.svc.cluster.local
            - nperf-1.nperf.${NAMESPACE}.svc.cluster.local
            - nperf-2.nperf.${NAMESPACE}.svc.cluster.local
            - nperf-3.nperf.${NAMESPACE}.svc.cluster.local
            - nperf-4.nperf.${NAMESPACE}.svc.cluster.local
            - nperf-5.nperf.${NAMESPACE}.svc.cluster.local
          ports:
            - name: http1
              containerPort: 9999
            - name: http2
              containerPort: 10000
